### ISSUE TITLE
[BUG]: Stuck at default class selection screen

### ISSUE THREAD

**Issue by RichanoG** [openmultiplayer/server-beta#136]
# Description

Hello, I seem to be having some problems with class selection. I'm getting stuck at the default SA:MP class selection screen (see screenshot), after suiciding while I've pressed F4. This is happening after I have updated to build 6 (with the crash fixes). I'm using a slightly modified version of [weapon-config](https://github.com/oscar-broman/samp-weapon-config).

So far, I have discovered that moving back to build 5 or just removing weapon-config has fixed the bug. I do not know what exactly seems to be the problem yet.

# How to re-produce this bug

EDIT: Added code example
```Pawn
#include <a_samp>
#include <omp>
#include <Pawn.RakNet>
#include <crashdetect>
#include <YSI-Includes\YSI_Data\y_iterate>
#include <zcmd>

#if !defined WC_DEATH_WORLD
	#define WC_DEATH_WORLD 0x00DEAD00
#endif

forward DeathRespawn(playerid);

CMD:kill(playerid, params[])
{
	ApplyAnimation(playerid, "PED", "KO_skid_back", 4.1, 0, 0, 0, 1, 0, 1);
	SetTimerEx("DeathRespawn", 3000, false, "d", playerid);
	return 1;
}

public DeathRespawn(playerid)
{
	SetPlayerVirtualWorld(playerid, WC_DEATH_WORLD);
	//SetFakeFacingAngle(playerid, _);
	TogglePlayerSpectating(playerid, true);
	TogglePlayerSpectating(playerid, false);
	SendClientMessage(playerid, -1, "debug 3");

	ForceClassSelection(playerid);
	SetPlayerHealth(playerid, 0.0);
	SetPlayerVirtualWorld(playerid, WC_DEATH_WORLD);
	return 1;
}

public OnPlayerSpawn(playerid)
{
	SetPlayerVirtualWorld(playerid, 0);
	return 1;
}
```
High ping seems to make the bug appear more often (almost always).

1. Join the server and spawn
2. Press F4 and suicide somehow

![sa-mp-270](https://user-images.githubusercontent.com/54376805/178462802-eecd76c5-56f3-4b99-82cd-d70bac82df5d.png)

# Relevant log output

-

# open.mp server version

open.mp server public beta build 6 (with crash fixes)

# Operating system or distribution

Debian 11

# Contact information

Richano#9220
rishanogopal@gmail.com

# Additional information

-

**Comment by NexiusTailer** [comment]
> I'm using a slightly modified version of [weapon-config](https://github.com/oscar-broman/samp-weapon-config).

What exactly was modified there or you're just about its latest commits which add Pawn.RakNet support?

**Comment by RichanoG** [comment]
> > I'm using a slightly modified version of [weapon-config](https://github.com/oscar-broman/samp-weapon-config).
> 
> What exactly was modified there or you're just about its latest commits which add Pawn.RakNet support?

I'm using the version which includes Pawn.RakNet. But, accidentally, I mentioned the main weapon-config repo. I however was using [this](https://github.com/Zbyss/samp-weapon-config/tree/5cf8dfe3ce736358c9248b9f05cfb705d689a97f) version of weapon-config, forked by Zbyss. I've changed the healthbar textdraws to playertextdraws, removed check in `WC_SetSpawnInfo` (force setspawninfo) and I've commented some functions like, SetPlayerPos, SetSpawnInfo etc in `OnPlayerSpawn`.

**Comment by NexiusTailer** [comment]
So, probably some of your changes could lead to any of that. Check non-modified latest [Zbyss's](https://github.com/Zbyss/samp-weapon-config/tree/omp) or original [oscar-broman's](https://github.com/oscar-broman/samp-weapon-config) version to be sure they also reproduce listed issues.

**Comment by RichanoG** [comment]
> So, probably some of your changes could lead to any of that. Check non-modified latest [Zbyss's](https://github.com/Zbyss/samp-weapon-config/tree/omp) or original [oscar-broman's](https://github.com/oscar-broman/samp-weapon-config) version to be sure they also reproduce listed issues.

I have tested it on Zbyss's latest version of weapon-config and it still happens. I believe it should've been clear already out of what I said about it not happening on build 5, that it isn't my own doing.

**Comment by RichanoG** [comment]
> > So, probably some of your changes could lead to any of that. Check non-modified latest [Zbyss's](https://github.com/Zbyss/samp-weapon-config/tree/omp) or original [oscar-broman's](https://github.com/oscar-broman/samp-weapon-config) version to be sure they also reproduce listed issues.
> 
> I have tested it on Zbyss's latest version of weapon-config and it still happens. I believed it should've been clear already out of what I said about it not happening on build 5, that it isn't my own doing.

**Comment by NexiusTailer** [comment]
> I believed it should've been clear already out of what I said about it not happening on build 5, that it isn't my own doing.

Ah, okay, this actually makes this clear enough, I just probably missed this.

**Comment by ksenonadv** [comment]
Fixed next build.

**Comment by RichanoG** [comment]
Hello, this issue seems to be still present in build8. I've tested it with the code example above (with high ping).

**Comment by mixedthoughts** [comment]
weapon config with pawnraknet =  it skips your class selection and you spawn as CJ - without setplayergang settings.

**Comment by NexiusTailer** [comment]
> weapon config with pawnraknet = it skips your class selection and you spawn as CJ - without setplayergang, color, other settings.

Could you report this to the weapon-config repo with the most details, please?

**Comment by NexiusTailer** [comment]
I cannot reproduce the "stuck" in class selection itself, because `<<`, `>>` and `Spawn` buttons are still working (at least on the latest build 10), but I've noticed other problem when using the MCVE provided in first post:
![image](https://user-images.githubusercontent.com/13169094/190921116-b7419102-87d3-4e66-b097-afbd8f25a61f.png)
Every time "debug 3" prints in the chat, next OnPlayerStateChange will *always* be called with corrupted `oldstate` argument value (0), while in samp there will be valid previous state used by this player before callback is called.

**Comment by RichanoG** [comment]
> I cannot reproduce the "stuck" in class selection itself, because `<<`, `>>` and `Spawn` buttons are still working (at least on the latest build 10), but I've noticed other problem when using the MCVE provided in the first post: ![image](https://user-images.githubusercontent.com/13169094/190921116-b7419102-87d3-4e66-b097-afbd8f25a61f.png) Every time "debug 3" prints in the chat, next OnPlayerStateChange will **always** be called with corrupted `oldstate` argument value (0), while in samp there will be valid previous state used by this player before callback is called.
> 
> Used logging code from my side (besides the provided example):
> 
> ```pawn
> public OnPlayerStateChange(playerid, newstate, oldstate)
> {
> 	new string[145];
> 	format(string, sizeof string, "OnPlayerStateChange(playerid %d, newstate %d, oldstate %d) GPState: %d", playerid, newstate, oldstate, GetPlayerState(playerid));
> 	SendClientMessage(playerid, -1, string);
> 	return 1;
> }
> ```

I see that I haven't notified correctly that you should be on very high ping (300 ish). Could you try that and see if it still happens? This still happens to me with that kind of ping. It is harder to reproduce on low ping, but it does still happen on low ping.

**Comment by RichanoG** [comment]
FYI, I've tested @NexiusTailer's example combined with mine, and this is the result when the << >> spawn buttons do not react anymore:
![sa-mp-273](https://user-images.githubusercontent.com/54376805/207177290-e8c76548-b00f-43ca-b38b-c3988e95773b.png)

I do believe this might have something to do with issue https://github.com/openmultiplayer/server-beta/issues/88, but I'm not exactly sure, so just throwing this out here.

---

The code below is what I've used during this screenshot. Removing only the 2 `TogglePlayerSpectating` functions fixed the problem for me where the buttons didn't react.

```pawn
#include <a_samp>
#define STRCPY(%0,%1,%2) 				strcat((%0[0] = '\0', %0), %1, %2)
#include <omp>
#include <crashdetect>
#include <YSI-Includes\YSI_Data\y_iterate>
#include <zcmd>

#if !defined WC_DEATH_WORLD
	#define WC_DEATH_WORLD 0x00DEAD00
#endif

forward DeathRespawn(playerid);

CMD:kill(playerid, params[])
{
	new string[128];
	ApplyAnimation(playerid, "PED", "KO_skid_back", 4.1, 0, 0, 0, 1, 0, 1);
	SetTimerEx("DeathRespawn", 3000, false, "d", playerid);
	return 1;
}

public OnPlayerStateChange(playerid, newstate, oldstate)
{
	new string[145];
	format(string, sizeof string, "OnPlayerStateChange(playerid %d, newstate %d, oldstate %d) GPState: %d", playerid, newstate, oldstate, GetPlayerState(playerid));
	SendClientMessage(playerid, -1, string);
	return 1;
}

public DeathRespawn(playerid)
{
	new string[128];
	SetPlayerVirtualWorld(playerid, WC_DEATH_WORLD);
	//SetFakeFacingAngle(playerid, _);
	TogglePlayerSpectating(playerid, true);
	format(string, sizeof(string), "debug (1): state = %d", GetPlayerState(playerid));
	SendClientMessage(playerid, -1, string);
	TogglePlayerSpectating(playerid, false);
	format(string, sizeof(string), "debug (2): state = %d", GetPlayerState(playerid));
	SendClientMessage(playerid, -1, string);

	ForceClassSelection(playerid);
	SetPlayerHealth(playerid, 0.0);
	SetPlayerVirtualWorld(playerid, WC_DEATH_WORLD);
	format(string, sizeof(string), "debug (3): state = %d", GetPlayerState(playerid));
	SendClientMessage(playerid, -1, string);
	return 1;
}

public OnPlayerSpawn(playerid)
{
	SetPlayerVirtualWorld(playerid, 0);
	return 1;
}
```
